version: '3.3'
services:
  redis:
    image: redis:3.2.9
  server:
    build: ./server
    command: npm run ${SERVER_NPM_SCRIPT}
    volumes:
      - ./server:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "${PORT}:8000"
      - "9229:9229" # Debug port
    environment:
      DEBUG: ${DEBUG}
      SECRET: ${SECRET}
      CALLBACK_URL: ${CALLBACK_URL}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_SECRET: ${OAUTH_SECRET}
