version: '3.3'
services:
  # Node App
  redis:
    image: redis:3.2.9
  server:
    build: ./server
    command: npm run ${SERVER_NPM_SCRIPT}
    volumes:
      - ./server:/home/node/app
      - /home/node/app/node_modules
    ports:
      # - "${PORT}:8000"
      - "9229:9229" # Debug port
    environment:
      DEBUG: ${DEBUG}
      SECRET: ${SECRET}
      CALLBACK_URL: ${CALLBACK_URL}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_SECRET: ${OAUTH_SECRET}
  client:
    build: ./client
    command: npm run dev
    volumes:
      - ./client:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "${PORT}:8000"
    environment:
      DEBUG: ${DEBUG}
      NODE_ENV: development
  # Rails App
  db:
    image: postgres:9.6.4
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
      POSTGRES_DB: rails
  rails:
    build: ./server-rails
    command: ./dev.sh
    volumes:
      - ./server-rails:/home/rails/app
      - /home/rails/app/tmp
    ports:
      - "${PORT_RAILS}:8000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://rails:rails@db/rails?pool=5
