#!/usr/bin/env bash

set -e

if [ $# -gt 0 ]; then
  if [ "$1" == "cnpm" ]; then
    shift 1
    docker-compose exec client npm "$@"
  elif [ "$1" == "snpm" ]; then
    shift 1
    docker-compose exec server npm "$@"
  elif [ "$1" == "test" ]; then
    shift 1
    docker-compose run --rm server npm test "$@"
  elif [ "$1" == "test:watch" ]; then
    shift 1
    docker-compose run --rm server npm run test:watch "$@"
  elif [ "$1" == "lint" ]; then
    shift 1
    docker-compose run --rm client npm run lint"$@"
    docker-compose run --rm server npm run lint"$@"
  else
    echo "dev: Command not found."
    exit 1
  fi
else
  docker-compose ps
fi
